> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# My Numpy Five Functions


### Numpy Selected Functions(five):

Numpy arrays are a type of object that hold numeric data. Numpy arrays contain numbers in a row and column form.Numpy arrays can be 2-dimentional like the array above, but also 1-dimentional or n-dimentional.

Here are my five selected functions:

- np.empty()
- np.squeeze()
- np.mean()
- np.where()
- np.flatten()



In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalmoradia/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalmoradia/numpy-array-operations


'https://jovian.ai/vishalmoradia/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

# List of functions explained 
- function1 = np.empty()  
- function2 = np.squeeze()
- function3 = np.mean()
- function4 = np.where()
- function5 = flatten()

## Function 1 - np.empty ()

Numpy empty() allows user to quickly make an empty array of any desired shape and with any dtype required.

In [7]:

#creating an array an empty square array of dimensions 2X2
# arguments : 1. Shape, 2. dtype


emp_array = np.empty([2,2], dtype = int)


#np.empty() creates an array with random values

print ("Array is:", emp_array)

Array is: [[94686037173024              0]
 [             0              0]]


Explanation about example

In [12]:
# Example 2 - working
emp_array_2 = np.empty([3,3], dtype = int)

print("Array is:", emp_array_2)

Array is: [[ 94686038294432               0 140667833201280]
 [140668188119856 140668190555120 140668190901936]
 [140668191735728 140667833245936             240]]


Explanation about example

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
emp_array_3 = np.empty( dtype = int)

print("Array is:", emp_array_3)

TypeError: empty() missing required argument 'shape' (pos 1)

Empty() needs the shape as an argument. That is an mandatory agrument to be given in the function. 'dtype' argument can be considered optional. 

How to fix this error ?
As the error says, shape argument is missing and that is the required argument for function to give any output.
Correct Solution : 

emp_array_3 = np.empty(shape = [3,3],  dtype = int)

print("Array is:", emp_array_3)

Numpy empty() enables us to create any empty array with any choosen or given shape. It can create an array quickly of the desired shape.

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalmoradia/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalmoradia/numpy-array-operations


'https://jovian.ai/vishalmoradia/numpy-array-operations'

## Function 2 - np.squeeze()

Whenever we want to remove any dimension from the multidimensional array, we can use Numpy squeeze().

In [21]:
# Example 1 - working
arr_x = np.array([[[ 0, 9, 8, 7],
                   [ 6, 5, 4, 3],
                   [ 2, 1, 0, 9]]]) #shape of this array is (1, 3, 4)

np.squeeze(arr_x, axis = 0) #shape of resultant squeezed array is (3,4)

array([[0, 9, 8, 7],
       [6, 5, 4, 3],
       [2, 1, 0, 9]])

Explanation about example

In [23]:
# Example 2 - working
arr_y = np.array([[[ 0, 9, 8, 7],[ 6, 5, 4, 3],[ 2, 1, 0, 9], [4, 2, 4, 6]]])
arr_y.shape # shape of unsqueezed array is (1,4,4)

np.squeeze(arr_y, axis = 0) # shape of this array is (4,4)

array([[0, 9, 8, 7],
       [6, 5, 4, 3],
       [2, 1, 0, 9],
       [4, 2, 4, 6]])

Explanation about example

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
arr_z = np.array([[[ 0, 9, 8, 7],[ 6, 5, 4, 3],[ 2, 1, 0, 9], [4, 2, 4, 6]]])

np.squeeze(arr_y, axis = 1)

ValueError: cannot select an axis to squeeze out which has size not equal to one

Squeeze function takes two arguments, one is array name and other is axis. Axis represents the shape of a single dimensional entries subset and its value cannot be more than one and if it is more than one in any case, an error is thrown.

How to fix it ?
We can fix this error by making axis = 0
arr_z = np.array([[[ 0, 9, 8, 7],[ 6, 5, 4, 3],[ 2, 1, 0, 9], [4, 2, 4, 6]]])

np.squeeze(arr_y, axis = 0)


When we want to remove one dimension from the given multi-dimensional array, we make use of a function called squeeze() in NumPy.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalmoradia/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalmoradia/numpy-array-operations


'https://jovian.ai/vishalmoradia/numpy-array-operations'

## Function 3 - np.mean()

Numpy mean function is used to calculate arithmetic mean of all the numbers in the array. It takes the sum of all individual elements and then divide it by the total number of elements on the basis of the axis provided. 

In [30]:
# Example 1 - working
mean_array = np.array([[2,3,4,5], [3,5,2,7], [7,8,9,6]])

np.mean(mean_array, axis = 1) # this calculates the mean, of all elements in the row

array([3.5 , 4.25, 7.5 ])

Explanation about example

In [31]:
# Example 2 - working
mean_array = np.array([[2,3,4,5], [3,5,2,7], [7,8,9,6]])

np.mean(mean_array, axis = 0) # this calculates the mean of all elements in the column

array([4.        , 5.33333333, 5.        , 6.        ])

Explanation about example

In [36]:
# Example 3 - breaking (to illustrate when it breaks)

mean_array_1 = np.array([[2,3,4,5], [3,5,2,7], [7,8,9,4]])
mean_array_2 = np.array([[2,3,4,3], [3,9,2,7], [7,1,9,4]])

np.mean(mean_array_1, mean_array_2)

TypeError: only integer scalar arrays can be converted to a scalar index

Mean() cannot be used to take mean of two arrays. We can individually take out mean of both arrays and then make an array of those two mean values. 

How to fix it ?

Take the mean of the arrays individually. 

The function mean() in NumPy is very useful for calculating the arithmetic average of elements especially in terms of data given in array subsets. 

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalmoradia/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalmoradia/numpy-array-operations


'https://jovian.ai/vishalmoradia/numpy-array-operations'

## Function 4 - np.where()

This function is used when certain predetermined conditions with respect to the function arguments are met, the function returns to the user the precise indices of certain elements that are present in the array that the user has entered.

In [59]:
# Example 1 - working
arr_w = np.array([[10, 20, 30], [40, 50, 60]])

sol = np.where(arr_w>20) #  For each element which test to be true, to the numpy.where() captures the indices of \n
                         #  the element into a new array containing the indices of each of the element testing true.

print(arr_w[sol]) #this print the value passed through the condition given in the function

[30 40 50 60]


Explanation about example

In [55]:
# Example 2 - working
arr_w_2 = np.array([[4, 5, 6], [7, 8, 9]])

sol_2 = np.where((arr_w_2 < 9) & (arr_w_2 > 4)) # here at the time two conditions are met in the same function. 

print(arr_w_2[sol_2])

[5 6 7 8]


Explanation about example

In [64]:
# Example 3 - breaking (to illustrate when it breaks)
arr_w_3 = np.array([[2,3,4,5], [3,4,5, 6]])

np.where(arr_w_3>2, 'Greater than 2', arr_w_3)

array([['2', 'Greater than 2', 'Greater than 2', 'Greater than 2'],
       ['Greater than 2', 'Greater than 2', 'Greater than 2',
        'Greater than 2']], dtype='<U21')

Here syntax error is thrown as pass keyword is not allowed in the syntax of the function. In order to fix this we have to 
replace keyword with the array name. 

How to fix this ? 

arr_w_3 = np.array([[2,3,4,5], [3,4,5,3]])

np.where(arr_w_3>2, 'Greater than 2', arr_w_3)

It is a very helpful functions when dealing with large dataset. It serves as a solution against the creation of many additional arrays that stores new elements specifically which increased the processing time and reduces the verbosity of the program.

In [65]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalmoradia/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalmoradia/numpy-array-operations


'https://jovian.ai/vishalmoradia/numpy-array-operations'

## Function 5 - flatten()

Flatten function is defined as to flatten the given array of any 2- dimensional or any other multi-dimensional array into a one-dimensional array which is provided by the Python module.

In [78]:
# Example 1 - working
arr_f = np.array([[2,3,8], [4,5,9], [3,0,6]])

arr_f.flatten()

array([2, 3, 8, 4, 5, 9, 3, 0, 6])

Explanation about example

In [75]:
# Example 2 - working
# in flatten() there is a parameter called 'order'. By default order 'C' is taken where it means that given multidimensional array to a single dimension in row-wise order.
# Other values which can be given in order parameter is 'K', 'F', 'A'

arr_f2 = np.array([[2,3,8], [4,5,9], [3,0,6]])
arr_f.flatten(order = 'F') # this orders column-wise

array([2, 4, 3, 3, 5, 0, 8, 9, 6])

Explanation about example

In [76]:
# Example 3 - breaking (to illustrate when it breaks)
arr_f2 = np.array([[2,3,8], [4,5,9], [3,0,6]])
np.flatten(arr_f2)

AttributeError: module 'numpy' has no attribute 'flatten'

Syntax of this function is differnt than all the functions used above. When we call the Numpy flatten method, we need to call it as a method based of of an existing Numpy array.

How to fix this ?

Solution: arr_f = np.array([[2,3,8], [4,5,9], [3,0,6]])

arr_f.flatten() 

Numpy flatten changes the shape of a Numpy array from a multi-dimensional array, to a 1-dimensional array.

In [77]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalmoradia/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalmoradia/numpy-array-operations


'https://jovian.ai/vishalmoradia/numpy-array-operations'

## Conclusion

In this notebook I learnt five Numpy functions which are very important for data analysis. 

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* educuba.com : https://www.educba.com/
* sharpsightlabs.com : https://www.sharpsightlabs.com/blog/numpy-flatten/#numpy-review

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>